### ISSUE TITLE
How to pin addons versions?

### ISSUE THREAD

**Issue by jensens** [plone/plone.docker#100]
If I specify addons I would like to pins its versions. 
I.e otherwise I get a wrong version for PloneFormGen in Plone 4.3. 

Any hint how to achieve this?

**Comment by svx** [comment]
Here we go, for example with a custom.cfg :):

- https://docs.plone.org/manage/docker/docs/container-images/custom.html

and on GitHub:

- https://github.com/plone/plone.docker/blob/master/docs/container-images/custom.rst

**Comment by jensens** [comment]
@svx, it seems, with latest version of docker-images this is no longer supported.

**Comment by avoinea** [comment]
or if you're using the `ADDONS` env:
```
  docker run -e ADDONS="Products.PloneFormGen==1.8.5" plone:4.3
```

**Comment by avoinea** [comment]
@svx you should trigger docs update on docs.plone.org. See https://github.com/plone/plone.docker/blob/master/docs/container-images/custom.rst#dockerfile

**Comment by jensens** [comment]
@avoinea thanks, it works now! This should be documented in a more visible place (like in README).

**Comment by jensens** [comment]
Overall, this works like a charm! thanks for the great work!

**Comment by avoinea** [comment]
> This should be documented in a more visible place (like in README).

Done https://github.com/plone/plone.docker/commit/4ad1a5a7a8d91b4910a023ea1c347ad98d9b47af
