### ISSUE TITLE
5.1.2 image does not have TinyMCE toolbar icons.

### ISSUE THREAD

**Issue by yamadamasaki** [plone/plone.docker#101]
all tool icon looks like a small rectangle.

5.1.0 image does have.

**Comment by avoinea** [comment]
Can you please provide more details. As I see no issues within Edit Page. See screenshot:

![tinymce](https://user-images.githubusercontent.com/323385/41840623-e533db3a-786e-11e8-9e13-1a6914ea4391.png)

**Comment by yamadamasaki** [comment]
these are the screenshots. good one (5.1.0 image) and bad one (5.1.2 image).
all the same results for docker on macOS or docker on ubuntu/digitalocean.

when i use 5.1.0 image first, and then use 5.2.1 image + 5.1.0 data,
there's no problem (icons are displayed).

thank you for your efforts.

2018-06-25 17:58 GMT+09:00 Alin Voinea <notifications@github.com>:

**Comment by avoinea** [comment]
@yamadamasaki I'm afraid you forgot to upload the screenshots here.

**Comment by yamadamasaki** [comment]
could you see them?

![badone](https://user-images.githubusercontent.com/36925/41846081-8fefe870-78b0-11e8-889d-23e04c28ef4d.png)
![goodone](https://user-images.githubusercontent.com/36925/41846082-901e32ac-78b0-11e8-803c-70a6f8f14f90.png)

**Comment by avoinea** [comment]
@yamadamasaki now I do, thank you!

**Comment by avoinea** [comment]
@yamadamasaki I'm afraid I can't replicate your issue. I've run:
```
docker run -it --rm -p 8080:8080 plone/plone:5.1.2 fg
```

and this is what I get in firefox:

![tinymce-jp](https://user-images.githubusercontent.com/323385/41846774-78a87f0e-7880-11e8-82b0-fa717cff5bf2.png)

**Comment by yamadamasaki** [comment]
i understand that my situation is too specific rather than general issue.

when i find whats happen i'll tell you that.

thank you.

2018-06-25 20:04 GMT+09:00 Alin Voinea <notifications@github.com>:
