### ISSUE TITLE
Fix dockerfile

### ISSUE THREAD

**Issue by svx** [plone/plone.docker#11]
The dockerfile in https://github.com/plone/plone.docker/blob/master/5.0/Dockerfile is 'broken' if you run lint against it you get the following: 

![plone5-dockerlint](https://cloud.githubusercontent.com/assets/358860/12644850/23814ab6-c5c6-11e5-91fc-b1048c74c3c5.png)
 The use of ADD is not considered to be best practice any more, we should switch to COPY, see https://docs.docker.com/engine/articles/dockerfile_best-practices/#add-or-copy

**Comment by avoinea** [comment]
Fixed by #14
