### ISSUE TITLE
buildout not configured to detect themes added to a resource folder

### ISSUE THREAD

**Issue by pigeonflight** [plone/plone.docker#114]
When doing theme development, I would like to be able to mount a local `resources` folder to serve diazo themes from resources/theme/{mycustom.theme}

The standard docker command does mount the resources folder. But the resources folder is not configured within the buildout.cfg.
```
docker run -it -v $(pwd)/resources:/plone/instance/resources  -p 8080:8080 plone
```

I propose a modification to the buildout.cfg so that when the resources folder is mounted it will detect themes added to the `resources/theme` folder.
In the `buildout.cfg` add an  `[instance_base]` section that includes a `resources` entry:

```
[instance_base]
resources = ${buildout-directory}/resources
```

**Comment by avoinea** [comment]
I will take a look on this for the next release.

**Comment by pigeonflight** [comment]
This may be something to be done upstream in the unified installer. Or downstream in people's custom builds.

**Comment by avoinea** [comment]
Fixed.
