### ISSUE TITLE
Deprecated base image

### ISSUE THREAD

**Issue by tianon** [plone/plone.docker#115]
The `python:2.7-alpine3.7` base image is officially deprecated (removed back in https://github.com/docker-library/python/commit/9e930c58c833e4a245c3cf90e0d03b32e8a64e2e), and Python 2.7 in general has a short lifespan (EOL 2020).

**Comment by avoinea** [comment]
Will be fixed once https://github.com/docker-library/official-images/pull/6343 is merged ;)
