### ISSUE TITLE
Managing the admin password

### ISSUE THREAD

**Issue by pigeonflight** [plone/plone.docker#116]
When deploying plone.docker, what is the best practice for setting/overriding the admin password?

**Comment by aogilvie** [comment]
I found this is possible though the ZOPE 4.0 and Plone 5.2 `/manage` to access backend and clicking acl_users , users , then click password.

However, with Plone 5.0x I have not been able to do this. Help would be appreciated.

**Comment by avoinea** [comment]
I'm not sure what is your problem as I can't reproduce it.

I've done:

$ docker run -it --rm -p 8080:8080 plone:5.0

Then

http://localhost:8080/acl_users/manage_users?name=admin&submit=Edit

**Comment by aogilvie** [comment]
I can verify the above is working. I was serving an nginx virtualhost which seemed to be causing my issues for 5.0.
