### ISSUE TITLE
PLONE_VERSION does not always match version substring used on Launchpad

### ISSUE THREAD

**Issue by pigeonflight** [plone/plone.docker#117]
## Problem

When using the current Dockerfiles the available environment variables are not enough to represent the URL path the UnifiedInstaller.

## Details
The following environment variables are declared in the Dockerfile.

`PLONE_MAJOR` and   `PLONE_VERSION`

For the 5.2 release this might look like this:
```
    PLONE_MAJOR=5.2 
    PLONE_VERSION=5.2 
```

These values are used to build the URL path to the release in this form:
`https://launchpad.net/plone/$PLONE_MAJOR/$PLONE_VERSION/+download/Plone-$PLONE_VERSION-UnifiedInstaller.tgz`

**The resulting string would be:**

`https://launchpad.net/plone/5.2/5.2/+download/Plone-5.2-UnifiedInstaller.tgz`

**The actual string that we want is:**

`https://launchpad.net/plone/5.2/5.2/+download/Plone-5.2.0-UnifiedInstaller.tgz`

## Proposed Solution

There needs to be an additional variable. such as PLONE_VERSION_RELEASE or PLONE_MINOR which specifies the full release number/name.

For example for the 5.2 release this might look like this:
```
    PLONE_MAJOR=5.2 
    PLONE_VERSION=5.2 
    PLONE_VERSION_RELEASE=5.2.0 
```

We can then build the URL path to the release using a slight variation of the form currently used:
`https://launchpad.net/plone/$PLONE_MAJOR/$PLONE_VERSION/+download/Plone-$PLONE_VERSION_RELEASE-UnifiedInstaller.tgz`

**Comment by avoinea** [comment]
Thank you! 

PR merged.
