### ISSUE TITLE
5.2 final released

### ISSUE THREAD

**Issue by polyester** [plone/plone.docker#119]
5.2 is finally out. New images on Dockerhub would be great

**Comment by avoinea** [comment]
Updated https://hub.docker.com/r/plone/plone. 

I will submit a PR for the official one https://hub.docker.com/_/plone after we have plone/plone built and see that everything is ok ;)

**Comment by avoinea** [comment]
PR created https://github.com/docker-library/official-images/pull/6343

**Comment by avoinea** [comment]
Released https://github.com/docker-library/official-images/pull/6343

See https://hub.docker.com/_/plone
