### ISSUE TITLE
Debian-based images failing to build on non-amd64/i386 architectures

### ISSUE THREAD

**Issue by yosifkit** [plone/plone.docker#120]
```console
The following tags failed to build:
  - plone:5.2.0
  - plone:5.2.0-python2
```

From what I can tell, it looks like a system library, `libffi-dev`, is needed in the `buildDeps` to compile BTrees for architectures other than amd64 and i386 (since those are provided pre-compiled via pypa). I am uncertain if this means `libffi6` needs to be added to `runDeps` or not.

```
Getting distribution for 'BTrees==4.5.1'.
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
 #include <ffi.h>
                 ^
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1
An error occurred when trying to install /plone/buildout-cache/downloads/dist/BTrees-4.5.1.tar.gz. Look above this message for any errors that were output by easy_install.
```

You can see the full output in the most recent build logs: https://doi-janky.infosiftr.net/job/multiarch/view/images/view/plone/.

------------

**Edit:** it seems `libffi6` is already installed in the current image
```console
root@7bfffbcfae6d:/plone/instance# apt-get install libffi6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libffi6 is already the newest version (3.2.1-6).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

**Comment by avoinea** [comment]
PR https://github.com/docker-library/official-images/pull/6360
