### ISSUE TITLE
Include optional plonesite recipe to the build

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.docker#121]
Hi @avoinea @svx ,
I want to use Plone Docker image for put people easily on the right track while demoing/testing/using Volto.
However, people still have to create the Plone site and install some profiles in order to have it running. Would it be possible to add an (optional) plonesite recipe to the buildout?
Cheers,
V.

**Comment by avoinea** [comment]
What about this image https://hub.docker.com/r/plone/volto ?!

**Comment by avoinea** [comment]
Ops, that actually the volto app, not Plone :)

**Comment by avoinea** [comment]
@sneridagh What do you have in mind? Can you detail a little bit?

I can see we have https://hub.docker.com/r/plone/plone.restapi/tags but it seems un-maintained.

**Comment by sneridagh** [comment]
@avoinea That image is indeed unmaintained and since p.restapi is in core, is no longer useful.

Before 5.2 I had my own tailored image that at the end, it created the site and installed the packages needed (p.restapi, and other package that we have for configuring the site to have it Volto-ready).

This image was the one that we use in https://volto.kitconcept.com/ and it's the image that we recommend the people for demo/test Volto in Volto README.

So, I imagined that we could have the buildout recipe `collective.recipe.plonesite` that creates launches Zope and creates a new site with some configuration. I guess you might well know it. It  also able to install package(s). 

So my idea is: could we add `collective.recipe.plonesite` to the image buildout (optionally) and create a default `Plone` site on it and install a list of profiles?

**Comment by avoinea** [comment]
> Before 5.2 I had my own tailored image that at the end, it created the site and installed the packages needed (p.restapi, and other package that we have for configuring the site to have it Volto-ready).

Can I see the Dockerfile / buildout for it?

**Comment by sneridagh** [comment]
I use this:

```
[plonesite]
recipe = collective.recipe.plonesite
site-id = Plone
instance = instance
profiles-initial = Products.CMFPlone:dependencies
profiles =
    plonetheme.barceloneta:default
    plone.app.contenttypes:plone-content
    kitconcept.voltodemo:default
upgrade-portal = False
upgrade-all-profiles = False
site-replace = True
```

**Comment by avoinea** [comment]
@sneridagh @tisto I added the `SITE` environment variable that will trigger the Plone site creation. Still volto won't talk to Plone due to **missing CORS** policy that I still have to add.

How did I manage to make it work, for now:

```docker run -it --rm --name=plone -p 8080:8080 -e SITE=Plone -e ADDONS="kitconcept.voltodemo==1.4" -e ZCML="kitconcept.voltodemo.cors" plone/plone```

Now in order to add the default CORS policy for development, I could find this example:

```
<plone:CORSPolicy
    allow_origin="http://localhost:4300,http://127.0.0.1:4300,http://localhost:3000,http://127.0.0.1:3000"
    allow_methods="DELETE,GET,OPTIONS,PATCH,POST,PUT"
    allow_credentials="true"
    expose_headers="Content-Length,X-My-Header"
    allow_headers="Accept,Authorization,Content-Type,X-Custom-Header"
    max_age="3600"
    />
  </configure>
```

And I need to understand what is running on port `:4300` and if this is required or not?

If you have a better conf, I would appreciate if you'd share it here.

**Comment by sneridagh** [comment]
Wooohooo!! Thanks a lot! Wht do you need is already in place in the kitconcept.voltodemo package. There’s a ZCML module: kitconcept.voltodemo.cors so you can add -e ZCML=kitconcept.voltodemo.cors I will try it out later!

**Comment by sneridagh** [comment]
@avoinea It works like a charm! I didn't realize at first that you were already using the ZCML="kitconcept.voltodemo.cors" option (I was on the mobile, answered quickly). So all is done, somehow. 

The ports 4200 are the ones normally used by default by Angular apps. Probably they are there from some old tests, nothing related to Volto. I guess that for simplify we should only use the 3000 ones.

BTW, I also tried to use it with another different plone.restapi version (5.0.0) and buildout throws a conflict error T_T Have the possibility to use latest plone.restapi would be great. Do you think we can workaround it somehow?

`docker run -it --rm --name=plone -p 8080:8080 -e SITE=Plone -e ADDONS="kitconcept.voltodemo plone.restapi==5.0.0" -e ZCML="kitconcept.voltodemo.cors" plone/plone`

```
Installing instance.
Version and requirements information containing plone.restapi:
  [versions] constraint on plone.restapi: 4.3.1
  Base installation request: 'Plone', 'Pillow', 'plone.reload', 'kitconcept.voltodemo', 'plone.restapi==5.0.0', 'plone.recipe.zope2instance'
While:
  Installing instance.
Error: The requirement ('plone.restapi==5.0.0') is not allowed by your [versions] constraint (4.3.1)```

**Comment by avoinea** [comment]
> BTW, I also tried to use it with another different plone.restapi version (5.0.0) and buildout throws a conflict error T_T Having the ability to use latest plone.restapi would be great. Do you think we can workaround it somehow?

Indeed, I also had this issue, that's why I pinned voltodemo to 1.4 `ADDONS="kitconcept.voltodemo==1.4"` I'll see what we can do about it :wink:

**Comment by avoinea** [comment]
@sneridagh @tisto Does it make sense to also add support for Plone 4.3.19 and Plone 5.1.6 Docker images.

Does **plone.restapi & volto** work with these versions?

**Comment by avoinea** [comment]
@sneridagh For now I pinned **plone.restapi to 4.6.0** on **Plone 4.3.x.**:

https://github.com/plone/plone.docker/blob/5d1cbe75c654f8a079232d200aab9da414bf1cc9/4.3/4.3.19/alpine/buildout.cfg#L99

If you have a working Plone 4.3.x buildout with plone.restapi 5.0.0 please share :wink:

**Comment by avoinea** [comment]
Ok. Now we have **plone.restapi=5.0.2** in Plone **4.3.19**, **5.1.6** and **5.2.0**

On it's way to the official image: https://github.com/docker-library/official-images/pull/6928

**Comment by sneridagh** [comment]
Awesome!! Thanks, Alin!
Sorry for the late reply. Indeed, `plone.restapi` works down to Plone 4 (some features are Plone 5 only, but they are advanced ones), every basic feature should work in there too, even with Archetypes!
This is great, I will update the Volto docs accordingly pointing people to use the standard images to test Volto.

/cc @tisto do you think it's worth to add the docker option in the p.restapi documentation too? In case that someone want to test Plone with p.restapi installed by default. I think it might be interesting too.

**Comment by sneridagh** [comment]
@avoinea I just updated Volto docs pointing to the new image. Thanks for your awesome work!
https://github.com/plone/volto/blob/master/README.md
https://docs.voltocms.com/getting-started/install/#run-a-volto-ready-plone-docker-container

**Comment by avoinea** [comment]
@sneridagh As the PR https://github.com/docker-library/official-images/pull/6928 is merged now, you can switch to the official Plone image.

Also, the CORS are already shipped with the Docker official image, thus you can simply run:

```
$ docker run -e SITE=Plone -p 8080:8080 plone
```

**Comment by sneridagh** [comment]
@avoinea amended in the docs and readme!
