### ISSUE TITLE
Plone 4.3.19 is out

### ISSUE THREAD

**Issue by avoinea** [plone/plone.docker#122]
4.3.19 is ready for you.

Relevant links:

    https://dist.plone.org/release/4.3.19/versions.cfg
    http://plone.org/products/plone/releases/4.3.19
    https://launchpad.net/plone/+milestone/4.3.19

**Comment by phgv** [comment]
Hi, could you push plone 4.3.19 image to docker hub?

**Comment by avoinea** [comment]
Released https://github.com/docker-library/official-images/pull/6870

https://hub.docker.com/_/plone
