### ISSUE TITLE
Plone 5.1.6 is out

### ISSUE THREAD

**Issue by avoinea** [plone/plone.docker#123]
5.1.6 released.

Relevant links:

    https://dist.plone.org/release/5.1.6/versions.cfg
    http://plone.org/products/plone/releases/5.1.6
    https://launchpad.net/plone/+milestone/5.1.6

**Comment by avoinea** [comment]
Ops. There is no UnifiedInstaller.tgz at https://launchpad.net/plone/5.1/5.1.6. @esteele ?!

**Comment by esteele** [comment]
@avoinea The installer is coming. Steve is on vacation this week, but said he could probably get to it this weekend.

**Comment by avoinea** [comment]
Released https://github.com/docker-library/official-images/pull/6870

https://hub.docker.com/_/plone
