### ISSUE TITLE
RelStorage support

### ISSUE THREAD

**Issue by avoinea** [plone/plone.docker#124]
Add possibility to use RelStorage instead of ZEO via **environment variables** or **command**

**Comment by ericof** [comment]
@avoinea How do you plan to do this? 
Already having the eggs for RelStorage, Psycopg2, and Mysql available or trying to do that on startup?

**Comment by avoinea** [comment]
Yes, with the eggs already available. We already have a working image at EEA https://github.com/eea/eea.docker.plone

Play with it, and let me know what's missing / what we can reuse here.

**Comment by avoinea** [comment]
@ericof I also did some immutable  releases in case you want to avoid surprises https://github.com/eea/eea.docker.plone/releases :smile:

**Comment by ericof** [comment]
@avoinea Great! I will play with it. (Currently just trying to add Relstorage 3.0 to docker is painful thanks to the fact [perfmetrics](https://github.com/zodb/perfmetrics) does not have a Linux wheel

**Comment by ericof** [comment]
Not anymore, perfmetrics now has Linux wheels on pypi :-)
