### ISSUE TITLE
Permission denied using custom.cfg with 5.2-debian version

### ISSUE THREAD

**Issue by marcosamm** [plone/plone.docker#125]
I am using volume mapping for the custom.cfg file and am getting the following error message:

chown: changing ownership of '/plone/instance/custom.cfg': Permission denied

This problem does not occur in version 5.1-debian. The only change to the docker-compose.yml file was the version number (from 5.1 to 5.2).

docker-compose.yml
--------------------------------
version: "2.1"
services:
    zeoserver:
        image: plone:5.2
        restart: unless-stopped
        volumes:
            - ./plone/mycustom.cfg:/plone/instance/custom.cfg
        ports:
            - 8080:8080

**Comment by avoinea** [comment]
Can you share the `custom.cfg` file. Basically, this image was not meant to be used like that, but it is always an option :smile:

**Comment by avoinea** [comment]
@marcosamm ^

**Comment by marcosamm** [comment]
[buildout]
extends = buildout.cfg

find-links +=
  https://my.nexus.host/repository/python-releases/simple/

[backup]
archive_blob=true
compress_blob=true
gzip_blob=true
full=true

**Comment by avoinea** [comment]
Hmm, it works for me:

```
$ docker run -it --rm -v $(pwd)/custom.cfg:/plone/instance/custom.cfg -p 8080:8080 plone:5.2
Uninstalling backup.
Unused options for buildout: 'deprecation-warnings' 'effective-user'.
Updating instance.
Generated script '/plone/instance/bin/instance'.
Generated interpreter '/plone/instance/parts/instance/bin/interpreter'.
Updating zeoserver.
Updating repozo.
Generated script '/plone/instance/bin/repozo'.
Installing backup.
Generated script '/plone/instance/bin/backup'.
Generated script '/plone/instance/bin/snapshotbackup'.
Generated script '/plone/instance/bin/restore'.
Generated script '/plone/instance/bin/snapshotrestore'.
Updating zopepy.
Updating unifiedinstaller.
Updating precompiler.
Compiling Python files.
  File "/plone/buildout-cache/eggs/plone.staticresources-1.1.0-py3.7.egg/plone/staticresources/static/components/cs-jqtree-contextmenu/node_modules/jqtree/_entries/renumber.py", line 36
    print 'rename %s to %s' % (old_filename, new_filename)
                          ^
SyntaxError: invalid syntax

  File "/plone/buildout-cache/eggs/plone.staticresources-1.1.0-py3.7.egg/plone/staticresources/static/components/cs-jqtree-contextmenu/node_modules/jqtree/_entries/insert.py", line 44
    print 'rename %s to %s' % (old_filename, new_filename)
                          ^
SyntaxError: invalid syntax

  File "/plone/buildout-cache/eggs/zodbpickle-1.0.4-py3.7-linux-x86_64.egg/zodbpickle/pickletools_2.py", line 1803
    print "skipping %r: it doesn't look like an opcode name" % name
                                                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("skipping %r: it doesn't look like an opcode name" % name)?

  File "/plone/buildout-cache/eggs/zodbpickle-1.0.4-py3.7-linux-x86_64.egg/zodbpickle/pickle_2.py", line 882
    except _Stop, stopinst:
                ^
SyntaxError: invalid syntax

  File "/plone/buildout-cache/eggs/zodbpickle-1.0.4-py3.7-linux-x86_64.egg/zodbpickle/tests/pickletester_2.py", line 433
    x = [0, 1L, 2.0, 3.0+0j]
             ^
SyntaxError: invalid syntax

Compiling locale files.
Updating setpermissions.
setpermissions: Running # Dummy references to force this to execute after referenced parts
echo /data/backups yes > /dev/null
chmod 600 .installed.cfg
# Make sure anything we've created in var is r/w by our group
find /data -type d -exec chmod 770 {} \; 2> /dev/null
find /data -type f -exec chmod 660 {} \; 2> /dev/null
find /data -type d -exec chmod 770 {} \; 2> /dev/null
find /data -type f -exec chmod 660 {} \; 2> /dev/null
chmod 754 /plone/instance/bin/*
Updating zeo.
Updating mrbob.
Generated script '/plone/instance/bin/mrbob'.
/plone/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/Zope2/Startup/serve.py:271: DeprecationWarning: 'U' mode is deprecated
2019-11-05 07:04:52,944 WARNING [Init:89][MainThread] Class Products.CMFFormController.ControllerPythonScript.ControllerPythonScript has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
2019-11-05 07:04:52,948 WARNING [Init:89][MainThread] Class Products.CMFFormController.ControllerValidator.ControllerValidator has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
2019-11-05 07:04:53,415 INFO    [ZODB.blob:355][MainThread] (1) Blob directory `/data/blobstorage` is unused and has no layout marker set. Selected `bushy` layout. 
2019-11-05 07:04:53,415 INFO    [ZODB.blob:355][MainThread] (1) Blob temporary directory '/data/blobstorage/tmp' does not exist. Created new directory.
/plone/buildout-cache/eggs/pyScss-1.3.5-py3.7-linux-x86_64.egg/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
2019-11-05 07:04:57,382 WARNING [plone.behavior:172][MainThread] Specifying 'for' in behavior 'Tiles' if no 'factory' is given has no effect and is superfluous.
2019-11-05 07:04:59,084 INFO    [Zope:45][MainThread] Ready to handle requests
Starting server in PID 1.
Serving on http://0.0.0.0:8080
```

It may be **Selinux/AppArmor** on your system who's preventing **chown**. 
On which OS you're trying this?

You can try to **chown** to **500:500** on custom.cfg before running docker-compose up, or better **setfacl**

```
setfacl  -R -m u:500:rwX .
setfacl -dR -m u:500:rwX .
getfacl ,
docker-compose up
```

See https://docs.plone.org/manage/docker/docs/usage/addons.html#add-ons

**Comment by marcosamm** [comment]
Hi, @avoinea.
The error occurs on Red Hat Enterprise Linux. In ubuntu it did not occur, but changed the owner in the custom.cfg file on the host:

drwxr-xr-x 54 marcos marcos 4,0K nov  5 07:59 ..
-rw-rw-r--  1    500    500  180 nov  5 07:59 custom.cfg
-rw-rw-r--  1 marcos marcos  177 nov  5 09:11 docker-compose.yml


I believe the difference in behavior is in the file [5.2/5.2.0/debian/docker-entrypoint.sh](url) on lines 11 and 12:
`if [ -e "custom.cfg" ]; then
  if [ ! -e "bin/develop" ]; then
    buildout -c custom.cfg
    chown -R plone:plone /plone
    gosu plone python /docker-initialize.py
  fi
fi`

In version 5.1 of file [5.1/5.1.6/debian/docker-entrypoint.sh](url) there is no change of file owner and buildout is performed with user plone:
`if [ -e "custom.cfg" ]; then
  if [ ! -e "bin/develop" ]; then
    gosu plone buildout -c custom.cfg
    gosu plone python /docker-initialize.py
  fi
fi`

**Comment by marcosamm** [comment]
> Hmm, it works for me:
> 
> ```
> $ docker run -it --rm -v $(pwd)/custom.cfg:/plone/instance/custom.cfg -p 8080:8080 plone:5.2
> Uninstalling backup.
> Unused options for buildout: 'deprecation-warnings' 'effective-user'.
> Updating instance.
> Generated script '/plone/instance/bin/instance'.
> Generated interpreter '/plone/instance/parts/instance/bin/interpreter'.
> Updating zeoserver.
> Updating repozo.
> Generated script '/plone/instance/bin/repozo'.
> Installing backup.
> Generated script '/plone/instance/bin/backup'.
> Generated script '/plone/instance/bin/snapshotbackup'.
> Generated script '/plone/instance/bin/restore'.
> Generated script '/plone/instance/bin/snapshotrestore'.
> Updating zopepy.
> Updating unifiedinstaller.
> Updating precompiler.
> Compiling Python files.
>   File "/plone/buildout-cache/eggs/plone.staticresources-1.1.0-py3.7.egg/plone/staticresources/static/components/cs-jqtree-contextmenu/node_modules/jqtree/_entries/renumber.py", line 36
>     print 'rename %s to %s' % (old_filename, new_filename)
>                           ^
> SyntaxError: invalid syntax
> 
>   File "/plone/buildout-cache/eggs/plone.staticresources-1.1.0-py3.7.egg/plone/staticresources/static/components/cs-jqtree-contextmenu/node_modules/jqtree/_entries/insert.py", line 44
>     print 'rename %s to %s' % (old_filename, new_filename)
>                           ^
> SyntaxError: invalid syntax
> 
>   File "/plone/buildout-cache/eggs/zodbpickle-1.0.4-py3.7-linux-x86_64.egg/zodbpickle/pickletools_2.py", line 1803
>     print "skipping %r: it doesn't look like an opcode name" % name
>                                                            ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print("skipping %r: it doesn't look like an opcode name" % name)?
> 
>   File "/plone/buildout-cache/eggs/zodbpickle-1.0.4-py3.7-linux-x86_64.egg/zodbpickle/pickle_2.py", line 882
>     except _Stop, stopinst:
>                 ^
> SyntaxError: invalid syntax
> 
>   File "/plone/buildout-cache/eggs/zodbpickle-1.0.4-py3.7-linux-x86_64.egg/zodbpickle/tests/pickletester_2.py", line 433
>     x = [0, 1L, 2.0, 3.0+0j]
>              ^
> SyntaxError: invalid syntax
> 
> Compiling locale files.
> Updating setpermissions.
> setpermissions: Running # Dummy references to force this to execute after referenced parts
> echo /data/backups yes > /dev/null
> chmod 600 .installed.cfg
> # Make sure anything we've created in var is r/w by our group
> find /data -type d -exec chmod 770 {} \; 2> /dev/null
> find /data -type f -exec chmod 660 {} \; 2> /dev/null
> find /data -type d -exec chmod 770 {} \; 2> /dev/null
> find /data -type f -exec chmod 660 {} \; 2> /dev/null
> chmod 754 /plone/instance/bin/*
> Updating zeo.
> Updating mrbob.
> Generated script '/plone/instance/bin/mrbob'.
> /plone/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/Zope2/Startup/serve.py:271: DeprecationWarning: 'U' mode is deprecated
> 2019-11-05 07:04:52,944 WARNING [Init:89][MainThread] Class Products.CMFFormController.ControllerPythonScript.ControllerPythonScript has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
> 2019-11-05 07:04:52,948 WARNING [Init:89][MainThread] Class Products.CMFFormController.ControllerValidator.ControllerValidator has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
> 2019-11-05 07:04:53,415 INFO    [ZODB.blob:355][MainThread] (1) Blob directory `/data/blobstorage` is unused and has no layout marker set. Selected `bushy` layout. 
> 2019-11-05 07:04:53,415 INFO    [ZODB.blob:355][MainThread] (1) Blob temporary directory '/data/blobstorage/tmp' does not exist. Created new directory.
> /plone/buildout-cache/eggs/pyScss-1.3.5-py3.7-linux-x86_64.egg/scss/selector.py:54: FutureWarning: Possible nested set at position 329
>   ''', re.VERBOSE | re.MULTILINE)
> 2019-11-05 07:04:57,382 WARNING [plone.behavior:172][MainThread] Specifying 'for' in behavior 'Tiles' if no 'factory' is given has no effect and is superfluous.
> 2019-11-05 07:04:59,084 INFO    [Zope:45][MainThread] Ready to handle requests
> Starting server in PID 1.
> Serving on http://0.0.0.0:8080
> ```
> 
> It may be **Selinux/AppArmor** on your system who's preventing **chown**.
> On which OS you're trying this?
> 
> You can try to **chown** to **500:500** on custom.cfg before running docker-compose up, or better **setfacl**
> 
> ```
> setfacl  -R -m u:500:rwX .
> setfacl -dR -m u:500:rwX .
> getfacl .
> docker-compose up
> ```
> 
> See https://docs.plone.org/manage/docker/docs/usage/addons.html#add-ons

@avoinea 
Is it safe to allow changing host files from the container? Sensitive variables may change and improper products may be installed in case of attacks.

**Comment by avoinea** [comment]
>@avoinea
> Is it safe to allow changing host files from the container? Sensitive variables may change and improper > products may be installed in case of attacks.

NO, it's not safe. That's why you should AVOID mounting files from host to container in production.

You should always copy cfg file within your custom docker image. See:

https://docs.plone.org/manage/docker/docs/container-images/custom.html#id1

Same for volumes. Always use docker volumes in production.

**Comment by avoinea** [comment]
Thus, your **docker-compose.yml** should look like:

``` yml
version: "2.1"
services:
  zeoserver:
    build: .
    restart: unless-stopped
    ports:
    - 8080:8080
    volumes:
    - data:/data
```
And add a **Dockerfile** with:

``` Dockerfile
FROM plone:5.2.0
COPY plone/mycustom.cfg /plone/instance/site.cfg
RUN  gosu plone buildout -c site.cfg
```

Try to avoid using `custom.cfg` file name as it is a **trigger** to **re-run buildout** when container is initialized, thus the first run will take longer.
