### ISSUE TITLE
Mixed Content problem for Plone behind Traefik reverse proxy

### ISSUE THREAD

**Issue by sofyanthayf** [plone/plone.docker#126]
I just tried installing the Docker-based Plone, and it runs behind Traefik as a reverse proxy, but when I access it from a web browser, I get an error on the console like this:

> Mixed Content: The page at 'https://new.mydomain.id/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Roboto:400,300,700'. This request has been blocked; the content must be served over HTTP

> Mixed Content: The page at 'https://new.mydomain.id/' was loaded over HTTPS, but requested an insecure stylesheet 'http://new.mydomain.id/++resource++plone-admin-ui.css'. This request has been blocked; the content must be served over HTTPS.

Are there any special environment variables that can be passed to make all communication using HTTPS?

Previously, I installed the OJS3 web application behind the same reverse proxy, and got the same error message, but resolved by passing the environment variable `HTTPS=on` to the container.

I hope there are similar environment variables for Plone. I use Traefik 1.7.16

**Comment by avoinea** [comment]
@sofyanthayf Thank you for the report. It looks like an issue and I filled a ticket to the affected python package https://github.com/plone/Products.CMFPlone/issues/2981

See also https://docs.plone.org/manage/docker/docs/scaling/swarm.html#swarm on how to use Plone behind Traefik.

You usually use this first panel to create your Plone Site, after that your front-end should redirect traffic to the Plone instance.

I'm not familiar with Traefik mechanism of adding rewrite-rules, but here is an example for Apache: https://docs.plone.org/manage/deploying/front-end/apache.html#installing-apache-front-end-for-plone

**Comment by yurj** [comment]
for traefik 2.0 see https://community.plone.org/t/erro-https-com-traefik/19328/4

**Comment by auspex** [comment]
> See also https://docs.plone.org/manage/docker/docs/scaling/swarm.html#swarm on how to use Plone behind Traefik.

That link does not exist...
