### ISSUE TITLE
Create a first merge with eea.docker.plone

### ISSUE THREAD

**Issue by demarant** [plone/plone.docker#13]
The idea is to do a first merge most of the work done in [eea.docker.plone](https://github.com/eea/eea.docker.plone) into this plone repo ([as discussed](https://github.com/plone/documentation/pull/505#issuecomment-177194212))

We would also need to configure the [plone docker hub](https://hub.docker.com/r/plone/plone/) auto-builds for all docker images needed for both standalone and cluster setups (e.g. plone, zeo).

As a last option, If merging in this repo is not found possible, we would need to create another repo within plone.

**Comment by svx** [comment]
Just use create a new directory or create a own branch here, and everything will be fine :)

**Comment by demarant** [comment]
@svx 
sure, if we just had the write access ;) this repo does not seem to be shared with the developers team ...

**Comment by svx** [comment]
upps, done !

**Comment by demarant** [comment]
@avoinea @svx added to [our queue](https://taskman.eionet.europa.eu/issues/68842) :smile:
