### ISSUE TITLE
ADDONS and Custom Image

### ISSUE THREAD

**Issue by iham** [plone/plone.docker#131]
i might have read it wrong or not at all ...
according to the docs for Custom Docker Images and the environment vars of the plone docker using compose, i thought this is possible:

i added ADDONS='my.addon' according to the docs AND i created my own site.cfg just to add my own pypi-server with some packages not public listed. see #130 on that too.
... but never got that working as the initial run does either or; not both.

which is not great, but ok, but as for me: undocumented.

think of this scenario besides my fancy private pypi server ...

developing on git-repos i don't see i can add through the env-vars.

you might want to install some common addons, listed on pypi.
docs say: use ADDONS (handy for docker-compose too!)
but i also need to use some stuff from source; which is not an env-option. but as i know i can do that using a custom image and a site.cfg with my sources and auto-checkouts and such. you can try that, but it won't work.

i don't see, why not allow both: using env vars AND extending with my custom buildout.

**Comment by avoinea** [comment]
@iham You can use both, of course. 

You just need to call your file **develop.cfg** instead of **site.cfg**:

**Dockerfile**

```
FROM plone:5

COPY develop.cfg /plone/instance/
RUN buildout -c develop.cfg \
 && find /data  -not -user plone -exec chown plone:plone {} \+ \
 && find /plone -not -user plone -exec chown plone:plone {} \+
```

Now, because Plone image already provides a **develop.cfg** file and you may want to keep it, you can also extend it within your custom **develop.cfg**:

**develop.cfg**

```
[buildout]
extends = plone-develop.cfg
find-links = ...
```

**Dockerfile**
```
FROM plone:5
RUN mv /plone/instance/develop.cfg /plone/instance/plone-develop.cfg
COPY develop.cfg /plone/instance/
RUN buildout -c develop.cfg \
 && find /data  -not -user plone -exec chown plone:plone {} \+ \
 && find /plone -not -user plone -exec chown plone:plone {} \+

```

**Comment by iham** [comment]
> @iham You can use both, of course.
> 
> You just need to call your file **develop.cfg** instead of **site.cfg**:
> 
> **Dockerfile**
> 
> ```
> FROM plone:5
> 
> COPY develop.cfg /plone/instance/
> RUN buildout -c develop.cfg \
>  && find /data  -not -user plone -exec chown plone:plone {} \+ \
>  && find /plone -not -user plone -exec chown plone:plone {} \+
> ```
> 
> Now, because Plone image already provides a **develop.cfg** file and you may want to keep it, you can also extend it within your custom **develop.cfg**:
> 
> **develop.cfg**
> 
> ```
> [buildout]
> extends = plone-develop.cfg
> find-links = ...
> ```
> 
> **Dockerfile**
> 
> ```
> FROM plone:5
> RUN mv /plone/instance/develop.cfg /plone/instance/plone-develop.cfg
> COPY develop.cfg /plone/instance/
> RUN buildout -c develop.cfg \
>  && find /data  -not -user plone -exec chown plone:plone {} \+ \
>  && find /plone -not -user plone -exec chown plone:plone {} \+
> ```

awesome! thank you.

it would be great to have that documented somewhere :)
