### ISSUE TITLE
Question about folder volume `/data`.

### ISSUE THREAD

**Issue by chenliu1993** [plone/plone.docker#133]
Hi experts. I got a few questions about the VOLUME /data.

From the Dockerfile I can see that there is cmd:
`mkdir -p /data/filestorage` before VOLUME /data.
So when user doesn't specific a -v of this `/data` like `-v /path/on/user:/data`, docker will automatically assign a volume on host to map the `/data` folder.
My question is no matter docker creates this `/data` map folder on host or user specific a host path to map this `/data`, there is no `filestorage` under `/data`. Thus plone contaier will fail to run.

But the actual result is . docker run successfully, could any one know the reason? Thank you

**Comment by avoinea** [comment]
When you declare a folder like `/data` as `VOLUME`, everything inside is copied from docker image to docker container if you let docker manage your volumes (`docker run plone` or `docker run -v plone-data:/data plone`)

Think of it like a `class` vs `instance` of that class:

```python
>>> class Plone:
...   data = ('filestorage', 'blobstorage')
...   def __init__(self, data=None):
...       if data is not None:
...         self.data = data
... 
>>> container = Plone()
>>> container.data
('filestorage', 'blobstorage')
```

Now, when you mount an external volume like: `-v /var/local/data:/data` you basically tell Docker that  you already have the initial data structure and override the default one.

```python
container = Plone(data=())
container.data
()
```

Still, we will add the `mkdir -p /data/filestorage /data/blobstorage /data/zeoserver` in the future releases of https://github.com/plone/plone.docker/blob/master/5.2/5.2.1/debian/docker-entrypoint.sh as we experienced a lot of issues when using with other volume drivers (e.g.: `rancher-nfs`, `netapp`). This way, container will make sure it has the initial `data structure` before it starts.

**Comment by chenliu1993** [comment]
Thank you very much!!!!
