### ISSUE TITLE
Docker run output errors

### ISSUE THREAD

**Issue by sydoluciani** [plone/plone.docker#145]
Running below command as explained [here](https://github.com/plone/volto#bootstrap-the-plone-api-backend):
```
docker run -it --rm --name=plone -p 8080:8080 -e SITE=Plone -e ADDONS="kitconcept.volto" -e ZCML="kitconcept.volto.cors" -e PROFILES="kitconcept.volto:default-homepage" plone
```

Throws below errors:
```
/plone/buildout-cache/eggs/plone.app.contenttypes-2.1.10-py3.8.egg/plone/app/contenttypes/migration/utils.py:482: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if source_type is 'DX':
/plone/buildout-cache/eggs/plone.app.contenttypes-2.1.10-py3.8.egg/plone/app/contenttypes/migration/utils.py:483: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if target_type is 'AT' and not is_referenceable(source_obj):
  File "/plone/buildout-cache/eggs/plone.staticresources-1.3.2-py3.8.egg/plone/staticresources/static/components/jqtree/_entries/insert.py", line 44
    print 'rename %s to %s' % (old_filename, new_filename)
          ^
SyntaxError: invalid syntax

  File "/plone/buildout-cache/eggs/plone.staticresources-1.3.2-py3.8.egg/plone/staticresources/static/components/jqtree/_entries/renumber.py", line 36
    print 'rename %s to %s' % (old_filename, new_filename)
          ^
SyntaxError: invalid syntax

  File "/plone/buildout-cache/eggs/zodbpickle-2.0.0-py3.8-linux-x86_64.egg/zodbpickle/pickletools_2.py", line 1803
    print "skipping %r: it doesn't look like an opcode name" % name
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("skipping %r: it doesn't look like an opcode name" % name)?

  File "/plone/buildout-cache/eggs/zodbpickle-2.0.0-py3.8-linux-x86_64.egg/zodbpickle/pickle_2.py", line 882
    except _Stop, stopinst:
                ^
SyntaxError: invalid syntax

  File "/plone/buildout-cache/eggs/zodbpickle-2.0.0-py3.8-linux-x86_64.egg/zodbpickle/tests/pickletester_2.py", line 433
    x = [0, 1L, 2.0, 3.0+0j]
             ^
SyntaxError: invalid syntax
```

**Comment by avoinea** [comment]
@sydoluciani It's just a warning. As I can see the the Docker container continues to run and eventually you are able to access: http://localhost:8080/Plone

**Comment by sydoluciani** [comment]
@avoinea  You are right, docker starts, and I can access http://localhost:8080/Plone with no problem, however those are actually errors, they are not affecting the docker startup since these syntax errors either in test, or just print statement syntax error, but one is in pickle and it might affect plone functionality later on.

Those two related to zodbpickle needs to be reported to [zodbpickle](https://github.com/zopefoundation/zodbpickle),
please let me know if I should report the issue, but you need to fix [print statement](https://github.com/plone/plone.staticresources/blob/master/src/plone/staticresources/static/components/jqtree/_entries/renumber.py#L36) that is missing parentheses.

**Comment by sydoluciani** [comment]
@avoinea This is syntax error, and it won't affect docker startup, since the syntax error is in except statement and probably never happens, but still it is the quality of code to maintain. 

```
File "/plone/buildout-cache/eggs/zodbpickle-2.0.0-py3.8-linux-x86_64.egg/zodbpickle/pickle_2.py", line 882
    except _Stop, stopinst:
                ^
SyntaxError: invalid syntax
```

**Comment by avoinea** [comment]
@sydoluciani Thank you. Please report the issues on **zodbpickle** and **plone.staticresources** repos with reference to this one.
