### ISSUE TITLE
Create Plone 5.2.4 Docker image

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.docker#155]
With Plone 5.2.4 we again have a Unified Installer: https://launchpad.net/plone/5.2/5.2.4
We have uploaded both a tarball and a zip.
Can you create a Docker image?
(I am not using Docker myself.)

**Comment by pnicolli** [comment]
@mauritsvanrees thanks for the update. Just a double check in order to anticipate work correctly: will versions 5.1.7 and 4.3.20 be skipped as well? I mean the UnifiedInstaller of course.

**Comment by mauritsvanrees** [comment]
@jensens @tkimnguyen  Do you think a UnifiedInstaller for 4.3.20 and 5.1.7 is possible without too much hassle? My guess is no, but maybe you can surprise me. :-)

**Comment by jensens** [comment]
Nobody should use the 4.3 or 5.1 installer any longer - it is only relevant to build the Docker image. I would not publish them.
Overall the old installer should work, but someone need to handcraft it. I have no idea if it works friction-less.

I will put my energy into the new installer concept for Plone 6 - to much time lost in 5.2 already.

**Comment by avoinea** [comment]
Released https://hub.docker.com/_/plone

**Comment by mauritsvanrees** [comment]
Thanks!
