### ISSUE TITLE
how to install ipdb?

### ISSUE THREAD

**Issue by dready** [plone/plone.docker#17]
Hi,

i have troubles installing ipdb on the plone/plone:5 docker container. My steps where:

1. Start the container normally.
2. Connect to it using a different shell and calling 
`docker exec -it NAME bash`
3. install ipdb using the instances pip
`/plone/instance/bin/pip install --no-cache-dir ipdb`
4. stop the instance and start it in development mode as described in the doku:
`
./bin/instance stop
./bin/instance fg
`

Unfortunately i get an error from ipython... it will show the man page and the last two lines are:
`
[TerminalIPythonApp] CRITICAL | Bad config encountered during initialization:
[TerminalIPythonApp] CRITICAL | Unrecognized flag: '-C'
`

And i have no clue how to get the thing going...

pip show ipdb:
`
plone@1aa25821af98:/plone/instance$ ./bin/pip show ipdb
---
Metadata-Version: 1.1
Name: ipdb
Version: 0.8.2
Summary: IPython-enabled pdb
Home-page: https://github.com/gotcha/ipdb
Author: Godefroid Chapelle
Author-email: gotcha@bubblenet.be
License: GPL
Location: /plone/instance/lib/python2.7/site-packages
Requires: ipython, setuptools
Entry-points:
  [console_scripts]
  ipdb = ipdb.__main__:main
The directory '/home/plone/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
`

Please help!

thx

**Comment by avoinea** [comment]
The issue seems to be with latest ipdb version (v0.8.2). Try:

```
/plone/instance/bin/pip install ipdb==0.8.1
```

**Comment by dready** [comment]
thx works great!
