### ISSUE TITLE
docker networking

### ISSUE THREAD

**Issue by svx** [plone/plone.docker#21]
How far/deep we want to go into that ?

With Version:  1.10.1 docker got some interesting network stuff.

Examples: http://filipv.net/2016/02/17/docker-networking-overview/

**Comment by demarant** [comment]
@svx 
that's a good question!

we have not tried any of these new features yet, so we don't have any experience to document on it yet.
we are mostly using docker 1.7.x and 1.8.x. still ...

I personally think, we shouldn't go to deep in all docker features, we could give just basic example and than just point to docker documentation for further reading.

**Comment by svx** [comment]
@demarant we use the 'new' docker networking stack in production and it is working fine, but yeah it would go a bit too far +1 for a mention and link to the official docs

**Comment by demarant** [comment]
@svx that's great that u are using in production! We started early with multi-host and therefore we got into rancher for that functionality among other useful features. And I fully agree to keep it simple in our docs (and still complete) with link to official :)

**Comment by svx** [comment]
Ok closing this now :)
