### ISSUE TITLE
update to readme and usage documentation regarding persistent data and environment variables

### ISSUE THREAD

**Issue by demarant** [plone/plone.docker#22]
All the docker run examples in readme misses a very important aspect: the persistent data. Users not familiar with docker will just wonder. Experienced users know and will look in the Dockerfile for VOLUME declarations. 

However I think we must make the docker run examples more correct from the start, to avoid surprises for first time users.

the plone image is not ephemeral per se, it containes a dbms, by definition docker containers are ephemeral and all persistent data must be stored outside of the container. 

Therefore we must have docker run example in the readme that have both the bindmount -v or the data-container pattern. Not having this, makes it looks like the application is ephemeral, which is not the case. The plone image contains the database manager as well. 

We should therefore replace the run example as follow:

```console
 	$ docker run -v /path/to/filestorage:/data/filestorage -v /path/to/blobstorage:/data/blobstorage -d plone/plone
```

and a short line that it can be also done with data containers pattern.

the documentation also misses the environment variables explanations.

moreover, we must remove the older files Motivation and notes.

**Comment by demarant** [comment]
@svx  i deleted motivation and notes. they were obsolete and unnecessary at this stage. re-add if you think they are still needed

**Comment by svx** [comment]
What is with about, putting a big note/warning to the readme, telling that you should/want persistent data setup/storage and link to this in /docs, where we have examples and also links to the official docs ?

**Comment by demarant** [comment]
@svx
Yes, something like that. 
Most new docker users will wonder "where is my data stored"? How do I back it up? We should complete the docker run examples and add further examples in /docs :)

**Comment by demarant** [comment]
@svx I could do a simple PR if needed.

**Comment by svx** [comment]
Sure, go ahead ! :)

**Comment by avoinea** [comment]
Obsolete
