### ISSUE TITLE
support adding eggs via envirnoment variables

### ISSUE THREAD

**Issue by djay** [plone/plone.docker#25]
its very compelling to not have to learn buildout etc and instead have a one line install like

```
$ docker run -e BUILDOUT_EGGS=rapido.plone eeacms/plone
```

I understand this requires buildout on startup but only if you choose that method of installing eggs. I think the convenience, even just for demos, is worth it.

**Comment by demarant** [comment]
@djay indeed :+1: this is part of the [eeacms/plone image]( https://github.com/eea/eea.docker.plone#developing-plone-add-ons) 
we should bring those features as well into the plone official image

**Comment by svx** [comment]
+1 I totally agree, for demo situations this would be really nice to have

**Comment by djay** [comment]
@demarant yeah the work you guys did at giving lots of options on how to customise your plone image was really nice. I've not seen that many docker images that customisable.

**Comment by avoinea** [comment]
Indeed I didn't bring those features into the official image because of the **re-run of the buildout within the container** which would slow down the creation of the container and may led to bad impressions.

But yes, I also miss these features and I think that they are "a good to have". Thus, a big **+1** from me ;)

**Comment by djay** [comment]
@avoinea I think that could be avoided by checking if any variables have been set which require a buildout and then skip it if none exist. Also if the variables don't require network access like (eg no BUILDOUT_EGGS) then running it in offline mode is more reliable and faster.
I think to make that work you might need to limit what env vars are supported instead of your "anything in buildout" approach. 
Allowing to override anything in buildout is still possible. we use https://github.com/collective/collective.recipe.environment to do this in our docker images.

**Comment by avoinea** [comment]
Done. See https://github.com/plone/plone.docker/blob/master/docs/usage.rst#5-add-ons
