### ISSUE TITLE
Add rsync in image

### ISSUE THREAD

**Issue by caduvieira** [plone/plone.docker#34]
In plone:4.3.9 executing bin/backup from collective.recipe.backup fails.

"INFO: rsync -a  /data/blobstorage /data/blobstoragebackups/blobstorage.0
/bin/sh: 1: rsync: not found"

http://docs.plone.org/manage/deploying/backup.html

**Comment by avoinea** [comment]
rsync added. 

Docker images are being rebuilt right now and they'll be available in a couple of hours on Docker Hub
