### ISSUE TITLE
Zeopack host is always 127.0.0.1

### ISSUE THREAD

**Issue by caduvieira** [plone/plone.docker#39]
During buildout the default for bin/zeopack is to 127.0.0.1

In https://github.com/plone/plone.docker/blob/master/4.3/4.3.10/alpine/Dockerfile#L42 
the recipe is made but the 'zeo-address' is not present.

In bin/zeopack should have something like host = $ZEO_ADDRESS

**Comment by avoinea** [comment]
Fixed. See related commit
