### ISSUE TITLE
zeopack fails when packing blobstorage

### ISSUE THREAD

**Issue by allusa** [plone/plone.docker#40]
Executing `bin/zeopack` fails. Although filestorage is packed, blobstorage remains the same and an OSError exception is raisen.

Causes:

* ZODB pack expects `var/blobstorage` and `var/blobstorage.old` to be in the same filesystem

* `/data/blobstorage` and `/data/blobstorage.old` will be in different filesystems as they are different Volumes

Steps to reproduce:

* Create minimal `docker-compose.yml`::

```
version: '2'
services:
  zeo:
    image: plone/plone:5.0.4
    expose:
      - 8100
    command: "zeoserver"
  plone:
    image: plone/plone:5.0.4
    ports:
      - "8080:8080"
    environment:
      - ZEO_ADDRESS=zeo:8100
```

* Start `docker-compose -f docker-compose.yml up`

* Do some changes, e.g. create a site, upload some file and modify it...

* Pack database `docker-compose exec zeo /plone/instances/bin/zeopack -D 0`::

```
	Traceback (most recent call last):
	  File "./bin/zeopack", line 39, in <module>
	    sys.exit(plone.recipe.zeoserver.pack.main(host, port, unix, days, username, password, realm, blob_dir, storage))
	  File "/plone/buildout-cache/eggs/plone.recipe.zeoserver-1.2.8-py2.7.egg/plone/recipe/zeoserver/pack.py", line 58, in main
	    _main(*args, **kw)
	  File "/plone/buildout-cache/eggs/plone.recipe.zeoserver-1.2.8-py2.7.egg/plone/recipe/zeoserver/pack.py", line 39, in _main
	    cs.pack(wait=True, days=int(days))
	  File "/plone/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZEO/ClientStorage.py", line 916, in pack
	    return self._server.pack(t, wait)
	  File "/plone/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZEO/ServerStub.py", line 155, in pack
	    self.rpc.call('pack', t, wait)
	  File "/plone/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZEO/zrpc/connection.py", line 768, in call
	    raise inst # error raised by server
	OSError: [Errno 18] Invalid cross-device link
```

* Docker logs::

```
   zeo_1    | 2016-09-21T07:48:58 (::ffff:127.0.0.1:55882) pack(time=1474444138.065265) started...
   zeo_1    | 2016-09-21T07:48:58 (14) Error raised in delayed method
```

* Changes in filesytem:

  - /data/filestorage/Data.fs has been packed properly
  - /data/filestorage/Data.fs.old has been copied properly
  - /data/blobstorage/ has not been packed, it has the same size as before packing
  - /data/blobstorage.old/ has been created and it is empty

**Comment by allusa** [comment]
Some possible solutions:

* Export all `/data` as a volume instead of `/data/filestorage` and `/data/blobstorage`

* Mantain `/data/blobstorage` as a volume and store blobs inside a subdirectory `blob-storage = ${buildout:var-dir}/blobstorage/blobstorage`

* Disable the creation of `*.fs.old` and 'blobstorage.old' files with::

```
   [zeoserver]
   pack-keep-old = false
```

Perhaps this last one is the easiest to be inserted into the images?

**Comment by avoinea** [comment]
I think we can declare `/data` as volume, but I wonder what are the implications?

**Comment by avoinea** [comment]
> Mantain /data/blobstorage as a volume and store blobs inside a subdirectory blob-storage = ${buildout:var-dir}/blobstorage/blobstorage

This is not an option because it will break backward compatibility and will require user action to upgrade their deployments.

**Comment by avoinea** [comment]
Added `ZEO_PACK_KEEP_OLD` environment variable to easily set `pack-keep-old = false` on the fly. 

I'm also still considering `/data` as volume instead of `/data/filestorage` and `/data/blobstorage`

**Comment by avoinea** [comment]
> I think we can declare /data as volume, but I wonder what are the implications?

My concerns were about not breaking existing deployments based on this image.
When you have declared in `docker-compose.yml` volumes like:

```
volumes:
- plone-filestorage:/data/filestorage
- plone-blobstorage:/data/filestorage
```

What happens now is that it will add another volume for `/data`, keeping the ones for `filestorage` and `blobstorage`. 

Thus, even if you don't upgrade your docker-compose, it is backward compatible.

I already updated `Dockerfiles` and `documentation`. See related commits.

**Comment by allusa** [comment]
> My concerns were about not breaking existing deployments based on this image.

Yes, I think that a volume for `/data` is compatible with latter definitions for `/data/filestorage` and  `/data/blobstorage`, although you can not remove `/data` volume.

The other way round,  `/data/filestorage` and `/data/blobstorage` volume definitions in Dockerfile, was not overwrittable  with a docker-compose.yml generic volume like: 
```
volumes:
- plone-data:/data
````
Perhaps in future there will be a docker UNVOLUME instruction to manage these cases https://github.com/docker/docker/issues/3465. It seems that some docker images have removed the VOLUME instruction from Dockerfile to avoid conflicts like that.
