### ISSUE TITLE
Use Label in dockerfile

### ISSUE THREAD

**Issue by svx** [plone/plone.docker#43]
From the docker docs:

> The LABEL instruction adds metadata to an image. A LABEL is a key-value pair. To include spaces within a LABEL value, use quotes and backslashes as you would in command-line parsing. A few usage examples:
LABEL version="1.0"
LABEL description="This text illustrates \
that label-values can span multiple lines."

So we could use something like:
```
LABEL version="5.1"
```

or

```
LABEL Plone="5.1"
```

This is really helpful is you use docker api in combination with inspect, plus if you use GUIs like portainer, shipyard, kubernetes and I guess it also works with Rancher, it will give use useful info with one check.

**Comment by avoinea** [comment]
Already fixed.
