### ISSUE TITLE
Nightly build

### ISSUE THREAD

**Issue by gforcada** [plone/plone.docker#44]
As a completely inexpert on docker, how much effort would it take to create a nightly docker image out of 5.1/5.0/4.3 straight from buildout.coredev?

Specially so that instead of [saying this](https://community.plone.org/t/how-to-deal-with-numerous-immediate-bugs-in-plone-5/3037/8?u=gforcada) we could say: get the nightly docker image and double check if the bug is there.

The amount of effort on running a docker image compared to clone and run buildout from buildout.coredev is probably some orders of magnitude, specially if there is (I guess) some sort of GUI where you can install and manage that.

**Comment by svx** [comment]
@gforcada It is not *that* amount of work, but still ppl have to find time to do it, also there would be the question if we really need nightly ? 
IMHO weekly should be more than enough ?

We had some time ago, a nightly build done by jenkins, I do not know the status, maybe @bloodbare knows more about that.

**Comment by gforcada** [comment]
Yes, weekly would work as well, as long as it is in jenkins and the only effort is pushing a button the frequency does not matter that much...

About that, the jenkins job that existed not so long ago was doing this: https://github.com/plone/jenkins.plone.org/blob/master/jobs.yml#L374

So basically calling registry.hub.docker.com with some parameters... I guess there is some more work to do, right?

**Comment by gforcada** [comment]
But in general, given some pointers I could work on that at some point, as this can be really useful for casual testing and double checking issues, etc etc

**Comment by gforcada** [comment]
@svx we didn't reach any agreement here 😄 should we try again? I don't care if daily/hourly/weekly/monthly/etc I do care about having the pipeline/setup in place and then we can do a pillow fight about when to trigger that.

So, back to the beginning, is this the place where to have docker images that have the latest checkouts of 5.1, 5.0 and 4.3? We can start with 5.1 and then as that one is stable and working provide another for 4.3. Maybe there is not even need for a 5.0 anymore as 5.1 is getting closer.

**Comment by avoinea** [comment]
@gforcada I'd place the Dockerfile directly within the development buildout, as we did for plone.restapi. We can have a talk on gitter, if you want ;)

**Comment by gforcada** [comment]
I'm still not an expert in docker, but we have lots of docker things right? 🤔
