### ISSUE TITLE
Health Check or Container

### ISSUE THREAD

**Issue by svx** [plone/plone.docker#48]
@avoinea I started to use:
https://docs.docker.com/engine/reference/builder/#/healthcheck a lot, cause it is easy and you get stuff quickly via api, or you can hook it up to consul.

It is of course not 'real monitoring' but still I find it for example very useful :)

Would it worth to add it to the image, what do you think ?

Possible downside:

- we need curl in the image
- if ppl use different ports they first have to adjust the Dockerfile 

And here is how it looks like:
![docker-plone-healthcheck](https://cloud.githubusercontent.com/assets/358860/20383381/d1ac66a4-acaf-11e6-9023-ff94822e6af1.png)

**Comment by avoinea** [comment]
Interesting...

Still, I'm worried about backward compatibility. Also, you can easily accomplish this with:

```
$ docker run --help | grep health
      --health-cmd string           Command to run to check health
      --health-interval duration    Time between running the check
      --health-retries int          Consecutive failures needed to report unhealthy
      --health-timeout duration     Maximum time to allow one check to run
      --no-healthcheck              Disable any container-specified HEALTHCHECK
``` 

BUT, maybe with this, we can get rid of our custom HEALTH CHECK implementation within [docker-entrypoint.sh](https://github.com/plone/plone.docker/blob/master/5.0/5.0.6/debian/docker-entrypoint.sh#L44)

```
  pid=`$CMD status | sed 's/[^0-9]*//g'`
  if [ ! -z "$pid" ]; then
    echo "Application running on pid=$pid"
    sleep "$HEALTH_CHECK_TIMEOUT"
    while kill -0 "$pid" 2> /dev/null; do
      sleep "$HEALTH_CHECK_INTERVAL"
    done
  else
    echo "Application didn't start normally. Shutting down!"
    _stop
  fi
```

**Comment by demarant** [comment]
I am also interested in this use case, @svx I propose we provide an example of the usage in the documentation in a docker-compose.yml (from v2.1) for production in the style:

```
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost"]
    interval: 1m30s
    timeout: 10s
    retries: 3
```

**Comment by fabiorauber** [comment]
I think health checks should be more thorough. For instance, when a Zeo client is disconnected from the Zeo server, the healthcheck above will succeed, but Plone is not healthy.

**Comment by avoinea** [comment]
HEALTCHECK added to the latest releases (4.3.17, 5.1.x)
