### ISSUE TITLE
Docs about how to store data

### ISSUE THREAD

**Issue by svx** [plone/plone.docker#50]
Hey, @avoinea :)

What is your opinion ? Reading https://github.com/plone/plone.docker/blob/master/docs/usage.rst, I would like to change that a bit.

```
 Data volumes (suitable for production use)
```

```
Mount host directories as data volumes (suitable for development use)
```

I would like to remove  `(suitable for production use)` and `(suitable for development use)`

According to the official docker docs that is of course completely right :) But there are also plenty of reasons why lots of people do not do that, yet ? 

Maybe it would be OK to remove that and add more docs and links about data storage ?

:)

**Comment by avoinea** [comment]
Please do ;)

**Comment by MikeMichel** [comment]
Hi, i would like to add plone as a "clickstarter" for sloppy.io (hosting platform for docker). 

![image](https://cloud.githubusercontent.com/assets/8025931/23165828/519f16b6-f83e-11e6-9cb0-f275525f6159.png)

I see plone has just /data as volume. That's it? No database or other directories?

**Comment by avoinea** [comment]
@MikeMichel nope, everything is within '/data' if you use it as a standalone application. If you need to scale it, then you'll have to use `zeoserver` as DB backend. See https://github.com/plone/plone.docker#start-plone-within-a-zeo-cluster

**Comment by avoinea** [comment]
I think this is already covered within our docs https://docs.plone.org/manage/docker/docs/data/index.html
