### ISSUE TITLE
Check Images for Vulnerabilities ?

### ISSUE THREAD

**Issue by svx** [plone/plone.docker#53]
Hi,
I started to use:
https://github.com/coreos/clair to check our images. Docs are here: https://coreos.com/clair/docs/latest/

This is nice, because now I get notified if our images [os level] are vulnerable, so that I can push up to date images. 

For doing so I use klar (https://github.com/optiopay/klar)

![klar-vmd-docs-check](https://cloud.githubusercontent.com/assets/358860/21383366/a9194df8-c765-11e6-8730-964fe6882012.png)

Would is be worth to implement something like that, should we use the 'docker hub build in' thing instead ?

**Comment by avoinea** [comment]
@svx 

AFAIK All official images are already scanned for vulnerabilities. See [tags](https://hub.docker.com/r/library/plone/tags/) as logged in

**Comment by svx** [comment]
Ok closing this then :)

Thanks !
