### ISSUE TITLE
Question: sudo vs gosu

### ISSUE THREAD

**Issue by svx** [plone/plone.docker#58]
Would it make sense to switch from sudo to gosu ?

Pro:
smaller and exactly written for that o docker

Con:
adds more complexity if you are not used to docker

**Comment by avoinea** [comment]
+1 as we already [use gosu](https://github.com/eea/eea.docker.kgs/blob/master/Dockerfile#L4) within our Plone base image.

**Comment by svx** [comment]
Yeah ! Cool ! +100 ! Closing this one now !
