### ISSUE TITLE
Clarify README.md

### ISSUE THREAD

**Issue by ju55i** [plone/plone.docker#69]
Make sure that the reader knows that single instance and cluster setup are mutually exclusive to each other. Also warnings about using the given setup in production environment. 

Clustered containers should run detached or instruct the reader to run the containers on separate terminals. 

Containers should have meaningful names (--name).

There should be an example for using the ADDONS environment variable because it is something people will probably look after getting the basic setup running. Also some information where to find more addons. How does this work with multiple addons (how are the addons separated)?

**Comment by svx** [comment]
@avoinea FYI, we're sprinting on the docs ! :)

**Comment by avoinea** [comment]
@svx Cool!

**Comment by svx** [comment]
done with https://github.com/plone/plone.docker/commit/be017507ba1f65c791a5c05ea55c80e71dfd9780
