### ISSUE TITLE
runtime package dependencies

### ISSUE THREAD

**Issue by svx** [plone/plone.docker#7]
We need to find out the exact runtime package dependencies for plone + pillow/image stuff.

Because we want to remove all not needed packages from the container, after building [running buildout].

**Comment by avoinea** [comment]
Plone will not start without:

Debian:
- libxml2
- libxslt1.1
- libjpeg62

Alpine:
- libxml2
- libxslt
- libjpeg-turbo

**Comment by svx** [comment]
Yeah, we should add that to the docs. I will do it later on
