### ISSUE TITLE
New Plone 4 release 

### ISSUE THREAD

**Issue by svx** [plone/plone.docker#75]
4.3.15 is ready for you.

Relevant links:

    https://dist.plone.org/release/4.3.15/versions.cfg
    http://plone.org/products/plone/releases/4.3.15
    https://launchpad.net/plone/+milestone/4.3.15

**Comment by avoinea** [comment]
- Built successfully @ https://hub.docker.com/r/plone/plone/builds/
- See docker-library/official-images#3257 for the Official Docker Image release
