### ISSUE TITLE
supprot arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [plone/plone.docker#76]
I was build plone.docker/5.0/5.0.8/debian/Dockerfile use FROM arm64v8/python:2.7-slim on arm64 architecture and successed.So I think I can be support arm64 and add it to the https://hub.docker.com/u/arm64v8/

**Comment by avoinea** [comment]
Added support for all architectures that python base image supports, including arm64. See https://hub.docker.com/_/plone/

**Comment by longquan7** [comment]
@avoinea I have a problem that why s the address is  https://hub.docker.com/_/plone/ instead of this https://hub.docker.com/u/arm64v8/

**Comment by avoinea** [comment]
See https://github.com/docker-library/official-images#architectures-other-than-amd64

> As of 2017-09-12, these other architectures are included under the non-prefixed images via "manifest lists" (also known as "indexes" in the OCI image specification), such that, for example, docker run hello-world should run as-is on all supported platforms.


Thus, running `docker run plone:5` should work on all supported platforms (see https://hub.docker.com/_/plone/ `Supported architectures:`)

**Comment by longquan7** [comment]
ok, thanks

**Comment by avoinea** [comment]
Also, I think it's a matter of docker hub sync, as I can see it is already under `ppc64le` namespace https://hub.docker.com/r/ppc64le/plone/
