### ISSUE TITLE
The day when PyPI decided to break the internet

### ISSUE THREAD

**Issue by avoinea** [plone/plone.docker#77]
Day: **Oct 26, 2017**
News: **no**, just an email https://mail.python.org/pipermail/distutils-sig/2017-October/031712.html

Secondary effects:

```
docker run --rm -e ADDONS="plone.restapi" plone:4
...
Couldn't find index page for 'plone.restapi' (maybe misspelled?)
Getting distribution for 'plone.restapi'.
Couldn't find index page for 'plone.restapi' (maybe misspelled?)
```

None of the stable tags that used to work before Oct 26 works anymore :(

**Comment by avoinea** [comment]
@svx 

This needs to update the Unified-Installer first.

**Comment by svx** [comment]
@avoinea yep ! Maybe @smcmahon is already working on it ?

**Comment by alecghica** [comment]
Maybe an issue should be added under https://github.com/plone/Installers-UnifiedInstaller/issues?

Looks like some work was done by @smcmahon under https://github.com/plone/Installers-UnifiedInstaller/commit/d35a79aceb5cf2344a5416a6f8c2c765ef911b61 but only for Plone 5?

**Comment by svx** [comment]
Closing this:

- This got fixed in the UI
- We are moving to another build setup for docker images, meaning we are not using UI as base anymore.

Anyway that means it is currently fixed and also fixed in/with the new setup
