### ISSUE TITLE
Add On Development

### ISSUE THREAD

**Issue by Pr0x1m4** [plone/plone.docker#78]
Hi, this has been extremely useful for development with plone. Thanks for making/maintaining it!

I'm having an issue where I'd like to use this to do Add-on development, I've seen from docs where a `PLONE_DEVELOP` environmental variable is used. Can you provide an example of how I'd use this to develop a local add-on?

**Comment by avoinea** [comment]
@Pr0x1m4 Unfortunately this functionality is broken due #77 

Basically, you have to run it like:

```
$ docker run -p 8080:8080 \
             -v $(pwd)/my.package:/plone/instance/src/my.package \
             -e ADDONS="my.package" \
             -e DEVELOP="src/my.package" \
         plone:5 fg
```

Don't forget to fix permissions:
```
$ setfacl  -R -m u:500:rwX $(pwd)/my.package
$ setfacl -dR -m u:500:rwX $(pwd)/my.package
$ getfacl $(pwd)/my.package
```

See [related docs](https://github.com/plone/plone.docker/blob/master/docs/usage/addons.rst)

**Comment by Pr0x1m4** [comment]
@avoinea I see, thanks for the quick response, I'll try it that way and appreciate the help!

**Comment by svx** [comment]
Since there was/is no more activity I will close this issue now.

Feel free to re-open of course !
