### ISSUE TITLE
update for hotfix 20171128?

### ISSUE THREAD

**Issue by tkimnguyen** [plone/plone.docker#80]
Hi - could we get the hotfix added please? Thanks :)

**Comment by svx** [comment]
@tkimnguyen docker images are based on the UI installer.
We do not add hotfixes or other stuff, it is all coming via the UI installer.

You can add it yourself if you want with: https://github.com/plone/plone.docker/blob/master/docs/usage/addons.rst, but this is more a 'workaround'

**Comment by avoinea** [comment]
@tkimnguyen @svx 

A good reason for new Plone releases ?!
* 5.0.9 or 5.0.10
* 4.3.16

This way maybe we also fix the `ADDONS` support broken by zc.buildout older than 2.9.5 (See #77)

**Comment by tkimnguyen** [comment]
Yeah, I will inquire about the possibility of a new release.  I will also look at adding the hotfix manually.

**Comment by tkimnguyen** [comment]
Re: https://github.com/plone/plone.docker/blob/master/docs/usage/addons.rst I see now what you mean by it being a workaround. What we need is for anyone using the Docker image to get the hotfix automatically. I guess that could mean also a new variant of 5.0.8 that just includes the hotfix (we've had those before; I just can't recall what specific version they were given).

**Comment by svx** [comment]
@tkimnguyen I guess I do not understand you :)

"What we need is for anyone using the Docker image to get the hotfix automatically."

This is not how docker works !

IMHO the best way would be:

- release a new UI installer with the Hotfix, we did that before in the past.
- if point one is done, we push a new docker image, with a new version

Still that does not mean people get this automatically, there are services like watchtower, but usually you do not use these in combination with a huge app like Plone.

**Comment by gforcada** [comment]
I'm not sure that all patches from the last hotfix are applied in all packages.

Usually, after a hotfix, we wait for all patches to be merged before a new release.

**Comment by svx** [comment]
Closing this one now :)
