### ISSUE TITLE
Upgrade to Docker HEALHCHECK

### ISSUE THREAD

**Issue by avoinea** [plone/plone.docker#83]
We should move our custom health-check from docker-entrypoint.sh to Dockerfile [HEALHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) directive. 

The only issue I can see is ZEO running on different port `8100`, thus I think we need a more complex check than `curl http://localhost:8080`

**Comment by svx** [comment]
One other disadvantage is that ``curl`` is a beast  and kind of huge (installs lots of stuff) :)

That was also the reason why we changed the Dockerfile to use ``wget`` in place of ``curl`` :)

**Comment by avoinea** [comment]
**HEALTHCKECK** added to the latest releases (5.1.x, 4.3.17)
