### ISSUE TITLE
Should we ditch UI as base ?

### ISSUE THREAD

**Issue by svx** [plone/plone.docker#84]
Hi,
looking through the download and install logs. 
I am wondering, should we stop using the Unified Installer as base ?

**Do not get me wrong the UI is great and super awesome !**
It is just that IMHO we do not need 98% of what it is doing.

Maybe it is an idea, to use the same buildout (easily done) but do the rest without the UI ?.

This would also

- decrease build time
- less mainating work
- less image layers 

Comments ? Suggestions ?

**Comment by avoinea** [comment]
@svx  I agree, as you said, hacking UI just to work, doesn't seem the right way to do it. Either we make the UI Docker aware, or we find a cleaner solution.

**Comment by avoinea** [comment]
Released! See https://github.com/docker-library/official-images/pull/4164 and https://hub.docker.com/_/plone/
