### ISSUE TITLE
Image build fails while executing UnifiedInstaller-5.1.0

### ISSUE THREAD

**Issue by skillfully** [plone/plone.docker#86]
Hi folks,
creating an image of 5.1/5.1.0/debian the installation fails executing the UnifiedInstaller which could not find <InstallerDir>/helper_scripts

Rreplacing installer version 5.1.0 with 5.1.0-r2 fixes the image build.

OS: Ubuntu 16.04.4 LTS
Docker: v17.05.0-ce

**Comment by avoinea** [comment]
https://github.com/plone/Installers-UnifiedInstaller/commit/947597676472d38326f122ff2785f6157ef3a9b8

**Comment by hipertracker** [comment]
This patch works like a charm :)

**Comment by avoinea** [comment]
Released! See https://github.com/docker-library/official-images/pull/4164 and https://hub.docker.com/_/plone/
