### ISSUE TITLE
New 4.3 release

### ISSUE THREAD

**Issue by svx** [plone/plone.docker#91]
4.3.17 is ready for you. 

Relevant links:  
* https://dist.plone.org/release/4.3.17/versions.cfg
* https://plone.org/download/releases/4.3.17
* https://launchpad.net/plone/+milestone/4.3.17

**Comment by avoinea** [comment]
Cool, then we can have a fully official Docker image without UI also for plone:4. 

Would be cool to also have a new 5.0 release to work on.

**Comment by svx** [comment]
Yeah I have to find some time, somehow :)

**Comment by avoinea** [comment]
Released! See https://github.com/docker-library/official-images/pull/4164 and https://hub.docker.com/_/plone/
