### ISSUE TITLE
New Plone 5.1.1 release

### ISSUE THREAD

**Issue by svx** [plone/plone.docker#92]
5.1.1 is ready for you. 

Relevant links:  
* https://dist.plone.org/release/5.1.1/versions.cfg
* http://plone.org/products/plone/releases/5.1.1 
* https://launchpad.net/plone/+milestone/5.1.1  

Please ping me when you've uploaded your installers so that I know to push the release out on plone.org.  Thanks, Eric

**Comment by hipertracker** [comment]
I created a fork, updated the Plone version and update MD5 hash string.  It was enough to build and run Plone 5.1.1 images from alpine, debian and pip, folders. It looks like all works fine. https://github.com/hipertracker/plone.docker/tree/master/5.1/5.1.1

**Comment by avoinea** [comment]
@hipertracker Yes, it's a [know issue](https://github.com/docker-library/official-images/pull/4164), that's why we work on to install Plone by using zc.buildout only (no Unified Installer). See [no-ui](https://github.com/plone/plone.docker/pull/87) pull-request.

**Comment by avoinea** [comment]
Released! See https://github.com/docker-library/official-images/pull/4164 and https://hub.docker.com/_/plone/
