### ISSUE TITLE
Hardcoded admin password in the released images :(

### ISSUE THREAD

**Issue by hipertracker** [plone/plone.docker#93]
All Plone images available at https://hub.docker.com/r/plone/plone/ have been build with a hardcoded, dumb admin password. Can I change it without creating my own customized image from scratch? How? If not, what is the purpose of releasing images with the hardcoded, so trivial, admin password?

**Comment by avoinea** [comment]
@hipertracker Of course you can change it. Within first screen click on the [Management Interface](http://localhost:8080/manage_main) > [acl_users](http://localhost:8080/acl_users/manage_main) > [admin](http://localhost:8080/acl_users/manage_users?name=admin&submit=Edit)

@svx We should add the above as the first step in documentation.

**Comment by hipertracker** [comment]
Sorry, it's all there. I was opening the acl_users from the specific Plone instance.
