### ISSUE TITLE
plone docker on https://plone.org/download

### ISSUE THREAD

**Issue by djay** [plone/plone.docker#94]
I know you guys are probably on this but just wanted to open the discussion about how far we are from this?

Ideally I'd like to see a one line docker command in the "try plone" section as well as some kind of one button (or close to) solutions for AWS and GCP since both should let you try plone on the free layer. 

And then perhaps a link to somewhere saying how to get a proper production environment with docker and plone

Sounds reasonable?
Seems really out of date our only one click solution is heroku.

**Comment by avoinea** [comment]
@esteele @svx  ^ ?!

**Comment by avoinea** [comment]
Link is there now. Thank you! 

https://plone.org/download
