### ISSUE TITLE
Broken docker images for 4.3.17 and 5.1+

### ISSUE THREAD

**Issue by david-batranu** [plone/plone.docker#97]
Creating a custom image, based on the 4.3.17 and 5.1+ images is impossible (following instructions from https://github.com/plone/plone.docker/blob/master/docs/container-images/custom.rst).

Running buildout results in the `python`, `buildout` and `pip` binaries having the `x` flag disabled for `other`.

This is caused by the [newly added symbolic links to the three binaries](https://github.com/plone/plone.docker/blob/master/4.3/4.3.17/debian/Dockerfile#L35-L37) (same for 5.1+ images). The links, combined with the unified installer [setpermissions part](https://github.com/plone/Installers-UnifiedInstaller/blob/7a73e8b9d529f363a3b18d153a5b602eac989302/base_skeleton/base.cfg#L214) results in the link targets being chmodded to `754`.

Steps to reproduce:

```
docker run --rm -it plone/plone:4.3.17 bash
gosu plone python --version
buildout
gosu plone python --version
```

result:
```
root@2d31008648c7:/plone/instance# gosu plone python --version
Python 2.7.15
root@2d31008648c7:/plone/instance# buildout
root@2d31008648c7:/plone/instance# gosu plone python --version
error: exec failed: permission denied
root@2d31008648c7:/plone/instance# ls -alh /usr/local/bin
-rwxr-xr-- 1 root staff  228 May 11 09:17 buildout
-rwxr-xr-- 1 root staff  211 May 11 09:17 pip
-rwxr-xr-- 1 root staff  25K May  5 03:30 python2.7
```

**Comment by avoinea** [comment]
Plone 4.3.18 and 5.1.4 released https://github.com/docker-library/official-images/pull/5014
